//
//  StateLinks.swift
//  MobileVoterOutreachApplication
//
//  Created by AK Alilonu on 7/8/18.
//  Copyright © 2018 Dylan  Irlbeck. All rights reserved.
//

import Foundation

//: Playground - noun: a place where people can play

import UIKit

import UIKit

class State {
    var name = String()
    var canRegisterOnline = Bool()
    var registerLink = String()
    var checkRegistrationLink = String()
    var canVoteEarly = Bool()
    var requestMailInBallot = String()
    var checkBallotLink = String()
    var findPollingPlaceLink = String()
}

func makeState(name: String, canRegisterOnline: Bool, registerLink: String, checkRegistrationLink: String, canVoteEarly: Bool, requestMailInBallot: String, checkBallotLink: String, findPollingPlaceLink: String) -> State {
    let s = State()
    s.name = name
    s.canRegisterOnline = canRegisterOnline
    s.registerLink = registerLink
    s.checkRegistrationLink = checkRegistrationLink
    s.canVoteEarly = canVoteEarly
    s.requestMailInBallot = requestMailInBallot
    s.checkBallotLink = checkBallotLink
    s.findPollingPlaceLink = findPollingPlaceLink
    return s
}

let stateNamesArray = ["Alaska",
                       "Alabama",
                       "Arkansas",
                       "Arizona",
                       "California",
                       "Colorado",
                       "Connecticut",
                       "District of Columbia",
                       "Delaware",
                       "Florida",
                       "Georgia",
                       "Hawaii",
                       "Iowa",
                       "Idaho",
                       "Illinois",
                       "Indiana",
                       "Kansas",
                       "Kentucky",
                       "Louisiana",
                       "Massachusetts",
                       "Maryland",
                       "Maine",
                       "Michigan",
                       "Minnesota",
                       "Missouri",
                       "Mississippi",
                       "Montana",
                       "North Carolina",
                       "North Dakota",
                       "Nebraska",
                       "New Hampshire",
                       "New Jersey",
                       "New Mexico",
                       "Nevada",
                       "New York",
                       "Ohio",
                       "Oklahoma",
                       "Oregon",
                       "Pennsylvania",
                       "Rhode Island",
                       "South Carolina",
                       "South Dakota",
                       "Tennessee",
                       "Texas",
                       "Utah",
                       "Virginia",
                       "Vermont",
                       "Washington",
                       "Wisconsin",
                       "West Virginia",
                       "Wyoming"]

let statesArray = [makeState(name: "Alabama",
                             canRegisterOnline: true,
                             registerLink: "https://www.alabamavotes.gov/olvr/default.aspx",
                             checkRegistrationLink: "https://myinfo.alabamavotes.gov/VoterView/RegistrantSearch.do",
                             canVoteEarly: false,
                             requestMailInBallot: "https://sos.alabama.gov/alabama-votes/voter/absentee-voting?m=voters",
                             checkBallotLink: "https://myinfo.alabamavotes.gov/VoterView/Home.do",
                             findPollingPlaceLink: "https://myinfo.alabamavotes.gov/VoterView/PollingPlaceSearch.do"),
                   makeState(name: "Alaska",
                             canRegisterOnline: true,
                             registerLink: "https://www.usvotefoundation.org/vote/voter-registration-absentee-voting.htm",
                             checkRegistrationLink: "https://myvoterinformation.alaska.gov",
                             canVoteEarly: true,
                             requestMailInBallot: "http://www.elections.alaska.gov/Core/votingbeforeelectionday.php",
                             checkBallotLink: "https://myvoterinformation.alaska.gov/",
                             findPollingPlaceLink: "https://myvoterinformation.alaska.gov/"),
                   makeState(name: "Arizona",
                             canRegisterOnline: true,
                             registerLink: "https://servicearizona.com/webapp/evoter/selectLanguage",
                             checkRegistrationLink: "https://voter.azsos.gov/VoterView/RegistrantSearch.do",
                             canVoteEarly: true,
                             requestMailInBallot: "https://azsos.gov/elections/voting-election/contact-information-county-election-officials",
                             checkBallotLink: "https://voter.azsos.gov/VoterView/Home.do",
                             findPollingPlaceLink: "https://voter.azsos.gov/VoterView/PollingPlaceSearch.do"),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: "")]

func initStateDictionary(withKeys: [String], andValues: [State]) -> Dictionary<String,State> {
    var stateDictionary = Dictionary<String,State>()
    stateDictionary.reserveCapacity(51)
    for stateName in withKeys {
        for state in andValues {
            print(stateName + "\n" + state.name)
            state.name = stateName
            stateDictionary.updateValue(state, forKey: stateName)
        }
    }
    return stateDictionary
}

let stateDictionary = initStateDictionary(withKeys: stateNamesArray, andValues: statesArray)

func getState(of stateName: String) -> State {
    return stateDictionary[stateName]!
}

getState(of: "Alabama")
