//
//  StateLinks.swift
//  MobileVoterOutreachApplication
//
//  Created by AK Alilonu on 7/8/18.
//  Copyright © 2018 Dylan  Irlbeck. All rights reserved.
//

import Foundation

import UIKit

// registerLink -> registerToVoteLink
// requestMailInBallot -> requestMailInBallotLink

class State {
    var name = String()
    var canRegisterOnline = Bool()
    var registerLink = String()
    var checkRegistrationLink = String()
    var canVoteEarly = Bool()
    var requestMailInBallot = String()
    var checkBallotLink = String()
    var findPollingPlaceLink = String()
}

func makeState(name: String, canRegisterOnline: Bool, registerLink: String, checkRegistrationLink: String, canVoteEarly: Bool, requestMailInBallot: String, checkBallotLink: String, findPollingPlaceLink: String) -> State {
    // initializes a states Bool values and hardcoded links
    let s = State()
    s.name = name
    s.canRegisterOnline = canRegisterOnline
    s.registerLink = registerLink
    s.checkRegistrationLink = checkRegistrationLink
    s.canVoteEarly = canVoteEarly
    s.requestMailInBallot = requestMailInBallot
    s.checkBallotLink = checkBallotLink
    s.findPollingPlaceLink = findPollingPlaceLink
    return s
}

// array of state names
let stateNamesArray = ["Alaska",
                       "Alabama",
                       "Arkansas",
                       "Arizona",
                       "California",
                       "Colorado",
                       "Connecticut",
                       "District of Columbia",
                       "Delaware",
                       "Florida",
                       "Georgia",
                       "Hawaii",
                       "Iowa",
                       "Idaho",
                       "Illinois",
                       "Indiana",
                       "Kansas",
                       "Kentucky",
                       "Louisiana",
                       "Massachusetts",
                       "Maryland",
                       "Maine",
                       "Michigan",
                       "Minnesota",
                       "Missouri",
                       "Mississippi",
                       "Montana",
                       "North Carolina",
                       "North Dakota",
                       "Nebraska",
                       "New Hampshire",
                       "New Jersey",
                       "New Mexico",
                       "Nevada",
                       "New York",
                       "Ohio",
                       "Oklahoma",
                       "Oregon",
                       "Pennsylvania",
                       "Rhode Island",
                       "South Carolina",
                       "South Dakota",
                       "Tennessee",
                       "Texas",
                       "Utah",
                       "Virginia",
                       "Vermont",
                       "Washington",
                       "Wisconsin",
                       "West Virginia",
                       "Wyoming"]

// array of state objects
let statesArray = [makeState(name: "Alabama",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: false,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "Alaska",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "Arizona",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: ""),
                   makeState(name: "",
                             canRegisterOnline: true,
                             registerLink: "",
                             checkRegistrationLink: "",
                             canVoteEarly: true,
                             requestMailInBallot: "",
                             checkBallotLink: "",
                             findPollingPlaceLink: "")]

func initStateDictionary(withKeys: [String], andValues: [State]) -> Dictionary<String,State> {
    // initializes dictionary of states
    var stateDictionary = Dictionary<String,State>()
    stateDictionary.reserveCapacity(51)
    for stateName in withKeys {
        for state in andValues {
            print(stateName + "\n" + state.name)
            state.name = stateName
            stateDictionary.updateValue(state, forKey: stateName)
        }
    }
    return stateDictionary
}

let stateDictionary = initStateDictionary(withKeys: stateNamesArray, andValues: statesArray)

func getLink(to search: String, in state: String) -> String {
    // creates link to website
    let space = "%20"
    let search = search.replacingOccurrences(of: " ", with: space)
    let link = "http://www.google.com/search?q=" + search + space + state + "&btnI"
    return link
}

func getState(of stateName: String) -> State {
    // completes state initialization
    var state = stateDictionary[stateName]!
    if state.registerLink == "" {
        state.registerLink = getLink(to: "register to vote in", in: stateName)
    }
    if state.checkRegistrationLink == "" {
        state.checkRegistrationLink = getLink(to: "am i registered to vote in", in: stateName)
    }
    if state.requestMailInBallot == "" {
        state.requestMailInBallot = getLink(to: "request ballot", in: stateName)
    }
    if state.checkBallotLink == "" {
        state.checkBallotLink = getLink(to: "where is my ballot", in: stateName)
    }
    if state.registerLink == "" {
        state.findPollingPlaceLink = getLink(to: "where is my polling place", in: stateName)
    }
    return state
}


